version: "3"

services:
    api:
        build: .
        container_name: pismo_api
        ports:
            - "8080:8080"
        environment:
            DATABASE_URL: mongodb://mongo:27017/
            DATABASE_NAME: pismo-db
            PORT: 8080
        networks:
            - product-network
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: mg-pismo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT: 
            MONGO_INITDB_PASSWORD: 
            MONGO_INITDB_DATABASE: pismo-db
               
        networks:
            - product-network

networks:
    product-network:
        driver:  "bridge"


  

