package router

import (
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
	"net/http"
	_ "projeto-pismo-api-go/docs" // docs is generated by Swag CLI, you have to import it.
	"projeto-pismo-api-go/pkg/api/controller"
)

func NewRARouter(accountController controller.AccountCtrl, transactionController controller.TransactionCtrl, healthController *controller.HealthHandler) http.Handler {
	router := mux.NewRouter()
	router.HandleFunc("/", handleHome)
	router.HandleFunc("/accounts", accountController.CreateAccount).Methods("POST")
	router.HandleFunc("/accounts/{id}", accountController.GetAccount).Methods("GET")
	router.HandleFunc("/transactions", transactionController.CreateTransaction).Methods("POST")
	router.HandleFunc("/health", healthController.Healthcheck).Methods("GET")

	// Swagger
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	return router
}

func handleHome(w http.ResponseWriter, r *http.Request) {
	msg := []byte("Welcome to Thiago API")
	w.Write(msg)
}
