application:
  name: pismo-stack
  brand: thiago
  flow: npf

deployments:
  container:
    image:
      repository: registry.pismo.com.br
      namespace: pismo-dev
      name: matrix-pismo-test
    resources:
      requests:
        cpu: 0.2
        memory: 512Mi
      limit:
        cpu: 0.2
        memory: 512Mi
    port: 8080
    probe:
      readiness:
        initialDelay: 5
        period: 5
      liveness:
        initialDelay: 5
        period: 5

expose:
  hosts:
    - host: pismo-stack-test-go.pkg.pismo.com.br
      paths:
        - /*
      ssl: false
      public: false
      config: {}

